---

- name: Determine cpu architecture
  shell: "dpkg --print-architecture"
  changed_when: false
  register: cpu_arch

- name: Create the node_exporter directory
  file:
    path: "{{ node_exporter_directory }}"
    state: directory

- name: Install node_exporter
  unarchive:
    remote_src: true
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ cpu_arch.stdout | trim }}.tar.gz"
    dest: "{{ node_exporter_directory }}"
    extra_opts: ["--strip-components=1"]
  notify: Restart node-exporter

- name: Configure systemd
  template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
  notify: Reload node-exporter

- name: Enable node_exporter
  service:
    name: node-exporter
    state: started
    enabled: true
