---

- name: install dependencies
  apt:
    name: software-properties-common
    cache_valid_time: 3600

- name: add the k8s key
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    dest: /tmp/k8s.key
  register: k8s_gpg_dl

- name: dearmor the gpg key
  shell: cat /tmp/k8s.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: k8s_gpg_dl.changed

- name: add the k8s repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    filename: kubernetes
  register: k8s_repo_file

- name: install k8s packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: "{{ k8s_gpg_dl.changed or k8s_repo_file.changed }}"

- when: ansible_swaptotal_mb > 0
  block:
    - name: disable swap
      shell: swapoff -a
  
    - name: remove swap from fstab
      lineinfile:
        regexp: '.*\s+swap\s+'
        path: /etc/fstab
        state: absent
