---

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install dependencies
  package:
    name: "{{ docker_deps }}"
    state: present

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install docker
  package:
    name: "{{ docker_pkgs }}"
    state: present

- name: Prevent docker upgrades (Ubuntu)
  dpkg_selections:
    name: "{{ item | regex_replace('=.+$', '') }}"
    selection: hold
  loop: "{{ docker_pkgs }}"
  when: ansible_os_family == "Debian"

- name: make sure the docker config directory exists
  file:
    path: /etc/docker/
    state: directory

- name: configure the docker daemon
  template:
    src: docker.daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: enable/restart docker

- name: create docker service directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: configure mount flags
  copy:
    src: systemd-mount-flags.conf
    dest: /etc/systemd/system/docker.service.d/mount-flags.conf
  register: mount_flags

- name: reload the docker daemon
  service:
    name: docker
    enabled: yes
    state: reloaded
  when: mount_flags.changed

- name: enable the docker daemon
  service:
    name: docker
    enabled: yes
    state: started

- name: create docker-compose directory
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    recurse: true

- name: install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: "0755"
  notify: enable/restart docker

- set_fact:
    deb_architecture: amd64
  when: ansible_architecture == "x86_64"

- set_fact:
    deb_architecture: arm64
  when: ansible_architecture == "aarch64"

- name: install compose-switch
  get_url:
    url: "https://github.com/docker/compose-switch/releases/download/v{{ docker_compose_switch_version }}/docker-compose-{{ ansible_system | lower }}-{{ deb_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: "0755"
  when: deb_architecture is defined

- debug:
    msg: "compose-switch is not supported on {{ ansible_architecture }}"
  when: deb_architecture is not defined
