---

- name: include os-specific variables
  include_vars: "{{ item }}" 
  loop:
    - main.yml
    - "{{ ansible_os_family }}.yml"

- name: install dependencies
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ deps }}"

- name: install docker
  executable: /bin/bash
  shell: curl -fsSL get.docker.com | sh

- name: include os-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: enable the docker daemon
  systemd:
    name: docker
    enabled: yes
    state: restarted


