---

- name: include os-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: install dependencies
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_deps }}"

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Install docker
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_pkgs }}"

- name: Prevent docker upgrades (Ubuntu)
  dpkg_selections:
    name: "{{ item | regex_replace('=.+$', '') }}"
    selection: hold
  loop: "{{ docker_pkgs }}"
  when: ansible_distribution == "Ubuntu"

- name: make sure the docker config directory exists
  file:
    path: /etc/docker/
    state: directory

- name: configure the docker daemon
  template:
    src: docker.daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: enable/restart docker

- name: enable the docker daemon
  service:
    name: docker
    enabled: yes
    state: started

