---

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install dependencies
  package:
    name: "{{ docker_deps }}"
    state: present

- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install docker
  package:
    name: "{{ docker_pkgs }}"
    state: present

- name: Prevent docker upgrades (Ubuntu)
  dpkg_selections:
    name: "{{ item | regex_replace('=.+$', '') }}"
    selection: hold
  loop: "{{ docker_pkgs }}"
  when: ansible_os_family == "Debian"

- name: make sure the docker config directory exists
  file:
    path: /etc/docker/
    state: directory

- name: configure the docker daemon
  template:
    src: docker.daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: enable/restart docker

- name: create docker service directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: configure mount flags
  copy:
    src: systemd-mount-flags.conf
    dest: /etc/systemd/system/docker.service.d/mount-flags.cona
  register: mount_flags

- name: reload the docker daemon
  service:
    name: docker
    enabled: yes
    state: reloaded
  when: mount_flags.changed

- name: enable the docker daemon
  service:
    name: docker
    enabled: yes
    state: started

- name: install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: "0755"

