---

- name: include os-specific variables
  include_vars: "{{ item }}" 
  loop:
    - main.yml
    - "{{ ansible_os_family }}.yml"

- name: install dependencies
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ deps }}"

- name: include os-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: install docker
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
