---

- name: Add authorized_keys
  authorized_key:
    user: "{{ item.user }}"
    state: "{{ item.state | default('present') }}"
    key: "{{ item.key }}"
  loop: "{{ authorized_keys }}"
  when: item.user is defined and item.key is defined

- name: Disable password logins
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PasswordAuthentication {% if disable_ssh_passwords %}no{% else %}yes{% endif %}"
    regexp: "^\\s*#?\\s*PasswordAuthentication .*"
  notify: Reload sshd
