---

- name: include os-specific variables
  include_vars: "{{ item }}"
  loop:
    - main.yml
    - "{{ ansible_os_family }}.yml"

- name: make sure docker is installed
  include_role:
    name: docker
  vars:
    docker_daemon_opts:
      userns-remap: default
      storage-driver: overlay2
      exec-opts: 
        - native.cgroupdriver=systemd
      log-driver: json-file
      log-opts:
        max-size: 100m  

- name: include os-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: check if swap enabled
  shell: swapon -s
  changed_when: False
  register: swap_enabled

- name: disable swap
  shell: swapoff -a
  when: swap_enabled.stdout != ""

- name: remove swap from fstab
  lineinfile:
    regexp: .*swap.*
    path: /etc/fstab
    state: absent

- name: configure mount propagation in docker
  blockinfile:
    block: |
      [Service]
      MountFlags=shared
    path: /etc/systemd/system/docker.service.d/mount-flags.conf
    create: yes
  notify: restart docker

- name: install kubernetes
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  notify: enable/restart kubernetes

# Required for flannel
- name: pass bridged traffic to iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
