---

docker_deps:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common
  - uidmap

# Latest as of 2022-01-24
docker_pkgs:
  - "containerd.io=1.4.12-1"
  - "docker-ce=5:20.10.12~3-0~{{ ansible_distribution | lower  }}-{{ ansible_lsb.codename }}"
  - "docker-ce-cli=5:20.10.12~3-0~{{ ansible_distribution | lower  }}-{{ ansible_lsb.codename }}"

