---

docker_deps:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - software-properties-common
  - uidmap

# K8s compatible as of 2020-06-15
# https://kubernetes.io/docs/setup/production-environment/container-runtimes
docker_pkgs:
  - containerd.io=1.2.13-2
  - "docker-ce=5:19.03.11~3-0~ubuntu-{{ ansible_lsb.codename }}"
  - "docker-ce-cli=5:19.03.11~3-0~ubuntu-{{ ansible_lsb.codename }}"

