---

- include_vars: "{{ ansible_os_family }}.yml"

- name: Add the vault gpg key
  apt_key:
    url: "{{ vault_gpg_key }}"
    state: present

- name: Add the vault repo
  apt_repository:
    repo: "{{ vault_repo }}"
    state: present
    update_cache: true

- name: Install vault
  package:
    name: vault
    state: present
 

