---

- name: include os-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Configure the vault server
  lineinfile:
    path: /etc/profile.d/vault.sh
    create: true
    mode: "0755"
    line: "export VAULT_ADDR={{ vault_addr }}"
    regexp: "export VAULT_ADDR=.*"
  notify: enable/restart vault

