---

- name: Install vault
  package:
    name: vault
    state: present

- name: Configure the vault server
  lineinfile:
    path: /etc/profile.d/vault.sh
    create: true
    mode: "0755"
    line: "export VAULT_ADDR={{ vault_addr }}"
    regexp: "export VAULT_ADDR=.*"

- name: Configure vault daemon
  service:
    name: vault
    state: "{{ 'started' if vault_server else 'stopped' }}"
    enabled: "{{ vault_server }}"
