- name: Set hostname
  hostname:
    name: "{{ set_hostname }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "127.0.0.1\\s+\\d{1-3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}"
    line: "127.0.1.1 {{ set_hostname }}"
