---

- name: install unattended-upgrades
  package:
    name:
      - unattended-upgrades 
      - apt-listchanges
      - mailutils
    state: present

- name: write /etc/apt/apt.conf.d/50unattended-upgrades
  template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: write /etc/apt/apt.conf.d/20auto-upgrades
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: make sure the timers are started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - apt-daily.timer
    - apt-daily-upgrade.timer
