---

- name: Reload node-exporter
  service:
    name: node-exporter
    state: restarted
    daemon_reload: true

- name: Restart node-exporter
  service:
    name: node-exporter
    state: restarted

