---

dependencies:
  - role: docker
    vars:
      pkgs:
        - docker-ce
      docker_daemon_opts:
        storage-driver: overlay2
        exec-opts: 
          - native.cgroupdriver=systemd
        log-driver: json-file
        log-opts:
          max-size: 100m  
