- name: Make sure lvm2 is installed
  package:
    name: lvm2
    state: latest

- name: Copy kernel config
  template:
    src: crio-modules.conf
    dest: /etc/modules-load.d/crio.conf

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
  loop: "{{ crio_kernel_modules }}"

- name: Configure sysctl
  sysctl:
    name: "{{ item }}"
    value: "1"
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/99-crio.conf
  loop: "{{ crio_sysctl_keys }}"

- name: Mount the cri-o volume
  mount:
    src: "{{ crio_volume }}" 
    path: /var/lib/containers/storage # cri-o default
    state: mounted
    fstype: ext4
    opts: noatime

- name: Set cri-o OS version
  set_fact:
    crio_os: "x{{ ansible_distribution }}_{{ ansible_distribution_version }}"

- name: Configure cri-o repos
  template:
    src: crio-repos.list
    dest: /etc/apt/sources.list.d/crio.list

- name: Add cri-o apt keys
  apt_key:
    url: "{{ item }}"
  loop:
    - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crio_os }}/Release.key
    - https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/{{ crio_os }}/Release.key

- name: Install cri-o
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - cri-o
    - cri-o-runc

- name: Make sure cri-o is started/enabled
  service:
    name: crio
    state: started
    enabled: yes
