- name: Make sure lvm2 is installed
  package:
    name: lvm2
    state: latest

- name: Copy kernel config
  template:
    src: crio-modules.conf
    dest: /etc/modules-load.d/crio.conf

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
  loop: "{{ crio_kernel_modules }}"

- name: Configure sysctl
  sysctl:
    name: "{{ item }}"
    value: "1"
    reload: yes
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/99-crio.conf
  loop: "{{ crio_sysctl_keys }}"

- name: Mount the cri-o volume
  mount:
    src: "{{ crio_volume }}" 
    path: /var/lib/containers/storage # cri-o default
    state: mounted
    fstype: ext4
    opts: noatime
  when: crio_volume is defined

- name: add the cri-o key
  get_url:
    url: "https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ crio_version }}/deb/Release.key"
    dest: /tmp/crio.key
  register: crio_gpg_dl

- name: dearmor the gpg key
  shell: cat /tmp/crio.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
  when: crio_gpg_dl.changed

- name: add the cri-o repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ crio_version }}/deb/ /"
    filename: cri-o
  register: crio_repo_file

- name: Install cri-o
  apt:
    name: cri-o
    state: latest
    update_cache: "{{ crio_gpg_dl.changed or crio_repo_file.changed }}"

- name: Make sure cri-o is started/enabled
  service:
    name: crio
    state: started
    enabled: yes
