---

- name: Install yum-utils
  package:
    name: yum-utils
    state: present

- name: Install the hashicorp repo
  shell: "yum-config-manager --add-repo {{ hashicorp_repo }}"
  args:
    creates: /etc/yum.repos.d/hashicorp.repo

