---

- name: add the atom gpg key
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey

- name: add the atom repository
  apt_repository:
    repo: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
    update_cache: yes
