---

- name: use python3 for this role
  set_fact:
    ansible_python_interpreter: /usr/bin/python3

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

# Firewalld is straight up broken in debian without this
- name: configure the firewalld daemon in debian-based systems
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^#?\s*IndividualCalls=.*'
    line: IndividualCalls=yes
  when: ansible_os_family == "Debian"
  register: firewalld_reconfigured

- name: configure firewalld zones
  copy:
    content: "{{ lookup('template', 'firewalld-zone.xml.j2', template_vars=item) }}"
    dest: "/etc/firewalld/zones/{{ item.name }}.xml"
  loop: "{{ firewalld_opts.zones | default([]) }}"
  register: firewalld_zones

- name: restart firewalld if it's been reconfigured
  service:
    name: firewalld
    state: reloaded
  when: firewalld_reconfigured.changed or firewalld_zones.changed

- name: make sure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: true

- name: determine the firewalld default zone
  shell: firewall-cmd --get-default-zone
  changed_when: false
  register: current_firewalld_default_zone

- name: set the firewalld default zone
  shell: "firewall-cmd --set-default-zone {{ firewalld_opts.default_zone | default('public') }}"
  when: "current_firewalld_default_zone.stdout.strip() != firewalld_opts.default_zone | default('public')"
