---

- name: make sure firewalld is installed
  package:
    name: firewalld
    state: present

- name: make sure firewalld is running/enabled
  service:
    name: firewalld
    state: started
    enabled: true

- name: determine the default zone
  shell: firewall-cmd --get-default-zone
  changed_when: false
  register: firewalld_current_default_zone

- name: determine the list of zones
  shell: firewall-cmd --get-zones
  changed_when: false
  register: firewalld_current_zones

- name: append the runtime zones to the configured zones
  set_fact:
    firewalld_zones: "{{ firewalld_zones | combine({item: {}}) }}"
  when: item not in firewalld_zones.keys()
  loop: "{{ firewalld_current_zones.stdout | split(' ') }}"

- name: template the firewalld zones
  template:
    src: zone.xml.j2
    dest: "{{ dest }}"
  vars:
    zone_name: "{{ item.key }}"
    zone: "{{ item.value }}"
    dest: "/etc/firewalld/zones/{{ item.key }}.xml"
  loop_control:
    label: "{{ dest }}"
  loop: "{{ firewalld_zones | dict2items }}"
  notify: firewalld reload

- name: set the default zone
  shell: "firewall-cmd --set-default-zone={{ firewalld_default_zone }}"
  when: firewalld_current_default_zone.stdout.strip() != firewalld_default_zone
  notify: firewalld reload
