---

- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- name: enable/start firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: restarted

- name: set default zone to 'public'
  shell: firewall-cmd --set-default-zone=public

- name: make sure ssh is in the 'public' zone
  firewalld:
    zone: public
    immediate: yes
    permanent: yes
    service: ssh
    state: enabled

- name: remove dhcpv6-client from 'public' zone
  firewalld:
    zone: public
    immediate: yes
    permanent: yes
    service: dhcpv6-client
    state: disabled

- name: add lo to 'trusted' zone
  firewalld:
    zone: trusted
    immediate: yes
    permanent: yes
    interface: lo
    state: enabled

- name: set 'public' target to 'DROP'
  shell: firewall-cmd --permanent --zone=public --set-target=DROP

- name: reload firewalld
  shell: firewall-cmd --reload
