- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: make sure timesyncd is enabled/running
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes

- name: check the timezone
  slurp:
    src: /etc/timezone
  register: current_timezone

- name: set the timezone
  shell: "timedatectl set-timezone '{{ timezone }}'"
  when: (current_timezone["content"] | b64decode | trim) != timezone

