---

- name: install dnsmasq
  package:
    name: dnsmasq
    state: present
  
- name: make sure dnsmasq is enabled
  service:
    name: dnsmasq
    enabled: yes

- name: write /etc/dnsmasq.conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq

- name: write /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  notify: restart dnsmasq
  
