---

- name: Install consul
  package:
    name: "consul={{ consul_version }}"
    state: present
  notify: enable/restart consul

- when: consul_server
  block:
    - name: Create the consul data directory
      file:
        path: /var/lib/consul
        state: directory
        owner: consul
        group: consul
        mode: "0700"

    - name: Create the consul service.d directory
      file:
        path: /etc/systemd/system/consul.service.d
        state: directory
      notify: systemctl daemon-reload

    - name: Configure systemd for consul server
      copy:
        src: service-sysd-override.conf
        dest: /etc/systemd/system/consul.service.d/overrides.conf
      notify: systemctl daemon-reload

- name: Check for firewalld
  shell: "which firewall-cmd"
  register: consul_firewalld
  changed_when: false
  failed_when: false

- when: consul_firewalld.rc == 0
  block:
    - name: Copy firewalld config files
      copy:
        src: "{{ item }}"
        dest: "/etc/firewalld/services/{{ item }}"
      loop:
        - consul-agent.xml
        - consul-server.xml
      register: consul_firewalld_files

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded
      when: consul_firewalld_files.changed

- name: include the envoy installation
  import_tasks: envoy.yml
  tags: envoy

